---
######### Dev Workflow  ########
on:
  pull_request:
    branches: [main]
    types:
      - closed
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Publish image to Azure Registry
        run: |
          docker build -t ${{ secrets.REGISTRY_DOMAIN }}/tdei-db-backup:${{ github.sha }} -t ${{ secrets.REGISTRY_DOMAIN }}/tdei-db-backup:${{ github.ref_name == 'master' && 'prod' || github.ref_name }}${{ github.ref_name != 'master' && '-latest' || 'latest' }} .
          docker push ${{ secrets.REGISTRY_DOMAIN }}/tdei-db-backup --all-tags
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.REGISTRY_DOMAIN }}/tdei-db-backup:${{ github.sha }}
